### ISSUE TITLE
Add VRE_API_TOKEN for vreapp

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/VREPaaS-helm-charts#26]
We need to pass the vreapi.auth.token to the vreapp for listing workflows

**Comment by gpelouze** [comment]
@skoulouzis the client components can’t read runtime environment variables (that’s why we had to serve the api and app on the same host). Can we use authentication only on `/workflows/submit`? That way we don’t need authentication from the vreapp.

**Comment by skoulouzis** [comment]
fixed by : https://github.com/QCDIS/VREPaaS/pull/136
